In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd

data = {
    "Age": [22, 25, 35, 45, 52, 23, 40, 55, 60, 30,
            27, 36, 48, 50, 29, 33, 41, 38, 26, 58],

    "Annual_Income": [25000, 30000, 50000, 70000, 90000,
                      28000, 65000, 85000, 95000, 45000,
                      32000, 55000, 75000, 88000, 40000,
                      52000, 68000, 62000, 35000, 98000],

    "Vehicle_Owner": [0,1,1,1,1,0,1,1,1,0,
                      0,1,1,1,0,1,1,1,0,1],

    "Previously_Insured":[0,0,1,1,1,0,1,1,1,0,
                          0,1,1,1,0,1,1,1,0,1],

    "Purchased":[0,0,1,1,1,0,1,1,1,0,
                 0,1,1,1,0,1,1,1,0,1]
}

df = pd.DataFrame(data)

df

    Age  Annual_Income  Vehicle_Owner  Previously_Insured  Purchased
0    22          25000              0                   0          0
1    25          30000              1                   0          0
2    35          50000              1                   1          1
3    45          70000              1                   1          1
4    52          90000              1                   1          1
5    23          28000              0                   0          0
6    40          65000              1                   1          1
7    55          85000              1                   1          1
8    60          95000              1                   1          1
9    30          45000              0                   0          0
10   27          32000              0                   0          0
11   36          55000              1                   1          1
12   48          75000              1                   1          1
13   50          88000              1                   1          1
14   29          40000              0                   0          0
15   33          52000              1                   1          1
16   41          68000              1                   1          1
17   38          62000              1                   1          1
18   26          35000              0                   0          0
19   58          98000              1                   1          1

In [3]:
df.to_csv("insurance.csv", index=False)

In [4]:
df.head()

   Age  Annual_Income  Vehicle_Owner  Previously_Insured  Purchased
0   22          25000              0                   0          0
1   25          30000              1                   0          0
2   35          50000              1                   1          1
3   45          70000              1                   1          1
4   52          90000              1                   1          1

In [6]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/14n4ZqSbJBcV3OJqnhY6wrqsSmkVjA2he74VkCxVvZDg/edit#gid=0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 20 non-null     int64
 1   Annual_Income       20 non-null     int64
 2   Vehicle_Owner       20 non-null     int64
 3   Previously_Insured  20 non-null     int64
 4   Purchased           20 non-null     int64
dtypes: int64(5)
memory usage: 932.0 bytes

In [8]:
X = df.drop("Purchased", axis=1)

y = df["Purchased"]

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)